### **Numpy Tutorial**

### Why Numpy??
- Numpy Array VS Pandas series

In [66]:
import numpy as np
import pandas as pd

a = np.arange(100)
aa = np.arange(100, 200)

s = pd.Series(a)
ss = pd.Series(aa)

i = np.random.choice(a, size=10)
i

array([64, 72, 71, 56, 21, 34, 80, 34, 36, 81])

In [67]:
#And here’s the performance comparison:
%timeit a[i]

%timeit s[i]

print()
print(a[i])
print()
print(s[i])

1.37 µs ± 35.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
506 µs ± 31.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

[64 72 71 56 21 34 80 34 36 81]

64    64
72    72
71    71
56    56
21    21
34    34
80    80
34    34
36    36
81    81
dtype: int32


In [68]:
%timeit a * aa

%timeit s * ss

717 ns ± 7.64 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
158 µs ± 11.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


To use Numpy, we first need to import the `numpy` package:

In [69]:
import numpy as np

### Upgrade Numpy
`pip install numpy --upgrade`
#### If it still doesn't work, try:

`pip install numpy --upgrade --ignore-installed`

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

### We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [70]:
a = np.array([1, 2, 3]) # Create a vector
print(type(a))
print("shape: ", a.shape)
print(a[0], a[1], a[2])
a[0] = 5 # Change an element of the array
print(a)                  

<class 'numpy.ndarray'>
shape:  (3,)
1 2 3
[5 2 3]


In [71]:
b = np.array([[1,2,3],
              [4,5,6]])   # Create a 2-D array
print(b, end = '\n\n')
print(b.shape, end = '\n\n')
print(b[0, 0], b[0, 1], b[1, 0])

[[1 2 3]
 [4 5 6]]

(2, 3)

1 2 4


In [72]:
c = np.array([[1,2,3]])   # Create a 2-D array when one dimension is 1
print(c)
print(c.shape)

[[1 2 3]]
(1, 3)


### Numpy also provides many functions to create arrays:

In [73]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [74]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [75]:
c = np.full((2,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [76]:
# The identity matrix plays a similar role in operations with matrices as the number 
# 1 plays in operations with real numbers. 
# The product of any square matrix and the appropriate identity matrix is always the 
# original matrix
d = np.eye(3) # Create a 2x2 identity matrix
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [77]:
e = np.random.random((2,2)) # Create an array filled with random values between 0 and 1
print(e)

[[0.85641733 0.42270998]
 [0.13682996 0.36216777]]


In [78]:
f = np.arange(12) # Create an array filled with values within a range
print(f.shape)
f

(12,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Array indexing

Numpy offers several ways to index into arrays.
- Check this stack overflow explanation for indexing [here](https://stackoverflow.com/questions/22053050/difference-between-numpy-array-shape-r-1-and-r)

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [79]:
a = np.array([[1,2,3,4],
              [5,6,7,8], 
              [9,10,11,12]])
print("shape: ", a.shape, end = '\n\n')
# [2 3]
c = a[1, 1:3]
print(c)
print()
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

shape:  (3, 4)

[6 7]

[[2 3]
 [6 7]]


In [80]:
a = np.array([[1,2, 3, 4],
              [5,6, 7, 8], 
              [9,10,11,12]])
# [[ 7  8]
#  [11 12]]
a[1:, 2:]


array([[ 7,  8],
       [11, 12]])

### A slice of an array is a view into the same data, so modifying it will modify the original array.

In [81]:
a = np.array([[1,2, 3, 4],
              [5,6, 7, 8], 
              [9,10,11,12]])

b = a[:2, 1:3]
print(b, end = '\n\n')

b[0, 0] = 77 # b[0, 0] is the same piece of data as a[0, 1]
print(a) 

[[2 3]
 [6 7]]

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. 

Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [82]:
# Create the following 2-D array with shape (3, 4)
a = np.array([[1,2,3,4], 
              [5,6,7,8], 
              [9,10,11,12]])

row_r1 = a[1, :]    # Vector view of the second row of a  
row_r2 = a[1:2, :]  # 2-D view of the second row of a
row_r3 = a[[1], :]  # 2-D view of the second row of a

print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [83]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


### Datatypes

- Every numpy array is a grid of elements of the same type. 
- Numpy provides a large set of numeric datatypes that you can use to construct arrays.
- Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype.
- Here is an example:

In [84]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype = np.float32)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)


int32 float64 float32


You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Array math

Check this wonderful post by Jai Alammar [here](http://jalammar.github.io/visual-numpy/)

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [85]:
x = np.array([[1,2],
              [3,4]], dtype=np.float64)

y = np.array([[5,6],
              [7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print()
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]

[[ 6.  8.]
 [10. 12.]]


In [86]:
x = np.array([[1,2],
              [3,4]], dtype=np.float64)

y = np.array([[5,6],
              [7,8]], dtype=np.float64)

# Elementwise difference; both produce the array
print(x - y)
print()
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]

[[-4. -4.]
 [-4. -4.]]


In [87]:
x = np.array([[1,2],
              [3,4]], dtype=np.float64)

y = np.array([[5,6],
              [7,8]], dtype=np.float64)

# Elementwise product; both produce the array
print(x * y)
print()
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]

[[ 5. 12.]
 [21. 32.]]


In [88]:
x = np.array([[1,2],
              [3,4]], dtype=np.float64)

y = np.array([[5,6],
              [7,8]], dtype=np.float64)

# Elementwise division; both produce the array
print(x / y)
print()
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [89]:
x = np.array([[1,2],
              [3,4]], dtype=np.float64)

print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


### Matrix Multipication

In [90]:
x = np.array([[1,2],
              [3,4],
              [5, 6]])

y = np.array([[5,6],
              [7,8]])

# Inner product of vectors; both produce 219
print(x.shape, y.shape, end = '\n\n')
print(x.dot(y), end = '\n\n')
print(np.dot(x, y), end = '\n\n')

(3, 2) (2, 2)

[[19 22]
 [43 50]
 [67 78]]

[[19 22]
 [43 50]
 [67 78]]



### You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [91]:
print(x @ y)

[[19 22]
 [43 50]
 [67 78]]


## 2-D array `@` Vector


![image info](https://i.ibb.co/sQWspGG/2d-vector.jpg)

In [94]:
print(x)
print()
print(y)

[[1 2]
 [3 4]
 [5 6]]

[[5 6]
 [7 8]]


In [95]:
# Matrix / vector product, both produce the rank 1 array [29 67]
x = np.array([[1, 2],
             [3, 4],
             [5, 6]])
v = np.array([9, 10])

print(x.shape, v.shape, end = '\n\n')
print(x.dot(v))
print()
print(np.dot(x, v))
print()
print(x @ v)
print((x @ v).shape)

(3, 2) (2,)

[ 29  67 105]

[ 29  67 105]

[ 29  67 105]
(3,)


In [96]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.shape, y.shape, end = '\n\n')
print()
print(x.dot(y))
print()
print(np.dot(x, y))
print()
print(x @ y)

(3, 2) (2, 2)


[[19 22]
 [43 50]
 [67 78]]

[[19 22]
 [43 50]
 [67 78]]

[[19 22]
 [43 50]
 [67 78]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [97]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [98]:
x = np.array([[1,2],
              [3,4],
              [5, 6]])
print(x, end = '\n\n')
print("transpose: \n", x.T)


[[1 2]
 [3 4]
 [5 6]]

transpose: 
 [[1 3 5]
 [2 4 6]]


In [99]:
# Transpose does nothig when one of the dimensions is 1
v = np.array([1,2,3])
print(v )
print("transpose\n", v.T)

[1 2 3]
transpose
 [1 2 3]


### Reshaping

In [100]:
# Compute outer product of vectors
x = np.array([[1,2],
              [3,4],
              [5, 6]])
print(x, end = '\n\n')
print(x.shape, end = '\n\n')

print(x.reshape(2, 3), end = '\n\n')
print(x.reshape(6, 1), end = '\n\n')
print(x.reshape(6))

[[1 2]
 [3 4]
 [5 6]]

(3, 2)

[[1 2 3]
 [4 5 6]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

[1 2 3 4 5 6]


In [101]:
 y = np.array([[1, 2, 6],
              [2, 3, 9],
              [4, 5, 15],
              [6, 7, 21]])
print(y.shape, end = '\n\n')    
print(y.reshape(3, -1))
print(y.reshape(3, -1).shape)

(4, 3)

[[ 1  2  6  2]
 [ 3  9  4  5]
 [15  6  7 21]]
(3, 4)


In [102]:
print(y.reshape(-1, 6))
print()

[[ 1  2  6  2  3  9]
 [ 4  5 15  6  7 21]]



In [103]:
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [104]:
x.shape

(3, 2)

### squeeze()

In [105]:
x = np.array([[1, 2]])
print(x)
print(x.shape)  # prints (2,)
print()


z_s = z.squeeze()
print(z_s)
print(z_s.shape)


[[1 2]]
(1, 2)

[1. 2.]
(2,)


In [106]:
x = np.zeros((2, 3, 1))

print(x)
print(x.shape)  # prints (2,)
print()

x_s = x.squeeze()
print(x_s.shape)

[[[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]]
(2, 3, 1)

(2, 3)


In [107]:
import numpy as np
m = np.array([[1, 2, 3],
              [2, 4, 6]])

print(m.shape)
len(m) # number of rows

(2, 3)


2

In [108]:
m = np.array([[1, 2, 3],
              [2, 4, 6]])
m[0], m[1]

(array([1, 2, 3]), array([2, 4, 6]))

In [109]:
m = np.array([[1, 2, 3],
              [2, 4, 6]])
print(m.shape)
print(len(m[0])) # number of elements in each row (columns)
len(m) # numebr of rows


(2, 3)
3


2

In [111]:
row = m.shape[0]
column = m.shape[1]

print(m.shape)
print(row, column)

(2, 3)
2 3


In [ ]:
for i in range(r):
    for j in range(c):
        print(m[i][j])